# Generated by Django 6.0.2 on 2026-02-15 23:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Pagado')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago')),
                ('nro_operacion', models.CharField(blank=True, help_text='Número de operación bancaria o código de transacción', max_length=50, verbose_name='Nro de Operación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cliente_pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='usuarios.perfilcliente', verbose_name='Cliente que Paga')),
                ('vendedor', models.ForeignKey(limit_choices_to={'rol': 'VENDEDOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_titular', models.CharField(help_text='DNI de la persona que usará este ticket', max_length=8, validators=[django.core.validators.RegexValidator(message='El DNI debe tener 8 dígitos', regex='^\\d{8}$')], verbose_name='DNI del Titular')),
                ('nombre_titular', models.CharField(max_length=200, verbose_name='Nombre del Titular')),
                ('codigo_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único imposible de clonar', unique=True, verbose_name='Código UUID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('USADO', 'Usado'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='eventos.zona', verbose_name='Zona')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['-fecha_venta'], name='ventas_vent_fecha_v_f04c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['vendedor', '-fecha_venta'], name='ventas_vent_vendedo_697b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente_pagador'], name='ventas_vent_cliente_5dc1e2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['codigo_uuid'], name='ventas_tick_codigo__742b72_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['dni_titular'], name='ventas_tick_dni_tit_3f8a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='ventas_tick_estado_3fc36b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['zona', 'estado'], name='ventas_tick_zona_id_c3d7f2_idx'),
        ),
    ]
