# Generated by Django 6.0.2 on 2026-03-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto de comisión cobrada (puede ser 0 si está incluida en precio)', max_digits=10, verbose_name='Comisión de Servicio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Suma de los precios de los tickets', max_digits=10, verbose_name='Subtotal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, help_text='Total cobrado al cliente (subtotal + comisión)', max_digits=10, verbose_name='Total Pagado'),
        ),
    ]
