# Generated by Django 6.0.2 on 2026-02-19 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('imagen_path', models.ImageField(blank=True, null=True, upload_to='eventos/categorias/', verbose_name='Imagen')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Desactivado')], default='1', max_length=1, verbose_name='Estado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('lugar', models.CharField(blank=True, help_text='Dirección exacta del evento', max_length=300, verbose_name='Lugar')),
                ('region', models.CharField(choices=[('Lima', 'Lima'), ('Arequipa', 'Arequipa'), ('Cusco', 'Cusco'), ('La Libertad', 'La Libertad'), ('Piura', 'Piura'), ('Lambayeque', 'Lambayeque'), ('Junín', 'Junín'), ('Puno', 'Puno'), ('Ica', 'Ica'), ('Áncash', 'Áncash'), ('Cajamarca', 'Cajamarca'), ('Loreto', 'Loreto'), ('San Martín', 'San Martín'), ('Ucayali', 'Ucayali'), ('Huánuco', 'Huánuco'), ('Ayacucho', 'Ayacucho'), ('Tacna', 'Tacna'), ('Moquegua', 'Moquegua'), ('Amazonas', 'Amazonas'), ('Apurímac', 'Apurímac'), ('Huancavelica', 'Huancavelica'), ('Madre de Dios', 'Madre de Dios'), ('Pasco', 'Pasco'), ('Tumbes', 'Tumbes'), ('Callao', 'Callao')], default='Lima', help_text='Región donde se realiza el evento', max_length=50, verbose_name='Región')),
                ('estado', models.CharField(choices=[('1', 'Próximo'), ('2', 'Activo'), ('3', 'Finalizado')], default='1', max_length=20, verbose_name='Estado')),
                ('activo', models.BooleanField(default=False, help_text='Solo un evento puede estar activo', verbose_name='Activo')),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen principal del evento (portada)', null=True, upload_to='eventos/principal/', verbose_name='Imagen Principal')),
                ('imagen_flyer', models.ImageField(blank=True, help_text='Flyer promocional del evento', null=True, upload_to='eventos/flyers/', verbose_name='Flyer')),
                ('imagen_banner', models.ImageField(blank=True, help_text='Banner para header o slider', null=True, upload_to='eventos/banners/', verbose_name='Banner')),
                ('imagen_cartel', models.ImageField(blank=True, help_text='Cartel o póster del evento', null=True, upload_to='eventos/carteles/', verbose_name='Cartel')),
                ('imagen_mapa_zonas', models.ImageField(blank=True, help_text='Plano/mapa con la distribución de zonas del local (VIP, General, etc.)', null=True, upload_to='eventos/mapas/', verbose_name='Mapa de Zonas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.categoria')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['evento', 'fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: VIP, General, Palco', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('capacidad_maxima', models.PositiveIntegerField(help_text='Número máximo de personas en esta zona', verbose_name='Capacidad Máxima')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='eventos.presentacion', verbose_name='Presentación')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['presentacion', 'precio'],
            },
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['activo', 'fecha_creacion'], name='eventos_eve_activo_6ef9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='zona',
            index=models.Index(fields=['presentacion', 'activo'], name='eventos_zon_present_f42263_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zona',
            unique_together={('presentacion', 'nombre')},
        ),
    ]
