# Generated by Django 6.0.2 on 2026-02-15 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('lugar', models.CharField(blank=True, max_length=300, verbose_name='Lugar')),
                ('estado', models.CharField(choices=[('1', 'Próximo'), ('2', 'Activo'), ('3', 'Finalizado')], default='1', max_length=20, verbose_name='Estado')),
                ('activo', models.BooleanField(default=False, help_text='Solo un evento puede estar activo', verbose_name='Activo')),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen principal del evento (portada)', null=True, upload_to='eventos/principal/', verbose_name='Imagen Principal')),
                ('imagen_flyer', models.ImageField(blank=True, help_text='Flyer promocional del evento', null=True, upload_to='eventos/flyers/', verbose_name='Flyer')),
                ('imagen_banner', models.ImageField(blank=True, help_text='Banner para header o slider', null=True, upload_to='eventos/banners/', verbose_name='Banner')),
                ('imagen_cartel', models.ImageField(blank=True, help_text='Cartel o póster del evento', null=True, upload_to='eventos/carteles/', verbose_name='Cartel')),
                ('imagen_mapa_zonas', models.ImageField(blank=True, help_text='Plano/mapa con la distribución de zonas del local (VIP, General, etc.)', null=True, upload_to='eventos/mapas/', verbose_name='Mapa de Zonas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['activo', 'fecha'], name='eventos_eve_activo_fa5258_idx')],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: VIP, General, Palco', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('capacidad_maxima', models.PositiveIntegerField(help_text='Número máximo de personas en esta zona', verbose_name='Capacidad Máxima')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['evento', 'precio'],
                'indexes': [models.Index(fields=['evento', 'activo'], name='eventos_zon_evento__d1781c_idx')],
                'unique_together': {('evento', 'nombre')},
            },
        ),
    ]
