# Generated by Django 6.0.2 on 2026-03-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='comision_incluida_precio',
            field=models.BooleanField(default=False, help_text='True: Comisión ya incluida en precio del ticket (organizador asume). False: Se cobra aparte al usuario como "Comisión de servicio"', verbose_name='Comisión incluida en precio'),
        ),
        migrations.AddField(
            model_name='evento',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión acordado con el organizador (ej: 8.00 para 8%)', max_digits=5, verbose_name='Comisión (%)'),
        ),
    ]
