# Generated by Django 6.0.2 on 2026-02-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Música', 'Música'), ('Deportes', 'Deportes'), ('Teatro', 'Teatro'), ('Conferencias', 'Conferencias'), ('Festivales', 'Festivales'), ('Gastronomía', 'Gastronomía'), ('Infantiles', 'Infantiles'), ('Otros', 'Otros')], default='Otros', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='evento',
            name='region',
            field=models.CharField(choices=[('Lima', 'Lima'), ('Arequipa', 'Arequipa'), ('Cusco', 'Cusco'), ('La Libertad', 'La Libertad'), ('Piura', 'Piura'), ('Lambayeque', 'Lambayeque'), ('Junín', 'Junín'), ('Puno', 'Puno'), ('Ica', 'Ica'), ('Áncash', 'Áncash'), ('Cajamarca', 'Cajamarca'), ('Loreto', 'Loreto'), ('San Martín', 'San Martín'), ('Ucayali', 'Ucayali'), ('Huánuco', 'Huánuco'), ('Ayacucho', 'Ayacucho'), ('Tacna', 'Tacna'), ('Moquegua', 'Moquegua'), ('Amazonas', 'Amazonas'), ('Apurímac', 'Apurímac'), ('Huancavelica', 'Huancavelica'), ('Madre de Dios', 'Madre de Dios'), ('Pasco', 'Pasco'), ('Tumbes', 'Tumbes'), ('Callao', 'Callao')], default='Lima', help_text='Región donde se realiza el evento', max_length=50, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(blank=True, help_text='Dirección exacta del evento', max_length=300, verbose_name='Lugar'),
        ),
    ]
