# Generated by Django 6.0.2 on 2026-02-19 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Ingreso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('dispositivo', models.CharField(blank=True, max_length=200, verbose_name='Dispositivo')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones', to='ventas.ticket', verbose_name='Ticket')),
                ('validador', models.ForeignKey(limit_choices_to={'rol': 'VALIDADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Validador')),
            ],
            options={
                'verbose_name': 'Validación de Ingreso',
                'verbose_name_plural': 'Validaciones de Ingreso',
                'ordering': ['-fecha_hora_ingreso'],
                'indexes': [models.Index(fields=['-fecha_hora_ingreso'], name='validacione_fecha_h_276bb7_idx'), models.Index(fields=['ticket'], name='validacione_ticket__eef03a_idx'), models.Index(fields=['validador', '-fecha_hora_ingreso'], name='validacione_validad_7405be_idx')],
            },
        ),
    ]
